spring.application.name=robostore

# 資料庫連線網址 (localhost:5432/你的資料庫名稱)
spring.datasource.url=jdbc:postgresql://localhost:5432/website
spring.datasource.username=root
spring.datasource.password=password

# JPA 相關設定
# update: 自動根據 Java 程式碼建立或修改資料表結構
spring.jpa.hibernate.ddl-auto=update
# 在控制台顯示執行的 SQL 語句，方便除錯
spring.jpa.show-sql=true
# 使用 PostgreSQL 的語法方言
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect